spring.application.name=url-shortener

server.port=${PORT:8080}

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/urlshortener}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:lithish7}

spring.sql.init.mode=always

spring.data.redis.url=${REDIS_URL:redis://localhost:6379}

spring.datasource.hikari.maximum-pool-size=10

app.base-url=${APP_BASE_URL:http://localhost:8080}
